nohup: ignoring input
Traceback (most recent call last):
  File "/common/home/qy129/DaRL/LibSignal/run.py", line 2, in <module>
    import trainer
  File "/common/home/qy129/DaRL/LibSignal/trainer/__init__.py", line 1, in <module>
    from .base_trainer import BaseTrainer
  File "/common/home/qy129/DaRL/LibSignal/trainer/base_trainer.py", line 5, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
nohup: ignoring input
/common/home/qy129/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/cuda/__init__.py:107: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at /opt/conda/conda-bld/pytorch_1682343997789/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
QCY: cuda is not available
YQC: you will use sumo~
building world...
Connection ID debug
Traceback (most recent call last):
  File "/common/home/qy129/DaRL/LibSignal/run.py", line 88, in <module>
    test.run()
  File "/common/home/qy129/DaRL/LibSignal/run.py", line 75, in run
    self.trainer = Registry.mapping['trainer_mapping']\
  File "/common/home/qy129/DaRL/LibSignal/trainer/tsc_trainer.py", line 25, in __init__
    super().__init__(
  File "/common/home/qy129/DaRL/LibSignal/trainer/base_trainer.py", line 50, in __init__
    self.create()
  File "/common/home/qy129/DaRL/LibSignal/trainer/base_trainer.py", line 110, in create
    self.create_agents()
  File "/common/home/qy129/DaRL/LibSignal/trainer/tsc_trainer.py", line 94, in create_agents
    agent = Registry.mapping['model_mapping'][Registry.mapping['command_mapping']['setting'].param['agent']](self.world, 0)
  File "/common/home/qy129/DaRL/LibSignal/agent/dqn.py", line 65, in __init__
    self.model = self._build_model()
  File "/common/home/qy129/DaRL/LibSignal/agent/dqn.py", line 191, in _build_model
    model = model.cuda()
  File "/common/home/qy129/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/common/home/qy129/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/common/home/qy129/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/common/home/qy129/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/common/home/qy129/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
